[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epsilon_transformers"
version = "0.0.1"

[tool.setuptools.find_packages]
include = ["epsilon_transformers"]

dependencies = [
    "transformers>=4.34.1",
    "transformer_lens>=1.12.0",
    "pytest>=7.4.4",
    "jaxtyping>=0.2.25",
    "plotly>=5.18.0",
    "numpy==1.26.3"
]